CREATE TABLE IF NOT EXISTS ingredient_master (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  category TEXT,
  image_path TEXT,
  nutrition_json JSONB,
  source TEXT DEFAULT 'IFCT',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS recipe_master (
  id SERIAL PRIMARY KEY,
  recipe_key TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  steps_json JSONB NOT NULL,
  servings INTEGER,
  image_path TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS recipe_ingredient_map (
  id SERIAL PRIMARY KEY,
  recipe_id INTEGER NOT NULL REFERENCES recipe_master(id) ON DELETE CASCADE,
  ingredient_id INTEGER NOT NULL REFERENCES ingredient_master(id) ON DELETE CASCADE,
  quantity TEXT,
  unit TEXT
);

CREATE TABLE IF NOT EXISTS recipe_search_log (
  id SERIAL PRIMARY KEY,
  recipe_key TEXT NOT NULL,
  searched_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_recipe_search_log_key ON recipe_search_log(recipe_key);

-- Likes and bookmarks
CREATE TABLE IF NOT EXISTS likes (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  recipe_id INTEGER REFERENCES recipe_master(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE (user_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS bookmarks (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  recipe_id INTEGER REFERENCES recipe_master(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE (user_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS videos (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  recipe_id INTEGER REFERENCES recipe_master(id) ON DELETE SET NULL,
  url TEXT NOT NULL,
  title TEXT,
  description TEXT,
  keywords TEXT,
  keyword TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE videos ADD COLUMN IF NOT EXISTS keyword TEXT;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS thumbnail TEXT;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS channel TEXT;
-- Add watch_count and structured keywords + category for admin management
ALTER TABLE IF EXISTS videos
  ADD COLUMN IF NOT EXISTS watch_count INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS videos
  ADD COLUMN IF NOT EXISTS keywords_json JSONB;
ALTER TABLE IF EXISTS videos
  ADD COLUMN IF NOT EXISTS category TEXT;

CREATE INDEX IF NOT EXISTS idx_video_keyword ON videos(keyword);
CREATE INDEX IF NOT EXISTS idx_video_created_date ON videos(created_at);

-- Users and authentication tables
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT UNIQUE,
  user_type TEXT,
  is_verified BOOLEAN DEFAULT FALSE,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Make phone nullable on existing installations
ALTER TABLE IF EXISTS users
  ALTER COLUMN phone DROP NOT NULL;

CREATE TABLE IF NOT EXISTS otp_code (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  phone TEXT,
  email TEXT,
  code TEXT NOT NULL,
  purpose TEXT NOT NULL, -- e.g., 'registration', 'login'
  expires_at TIMESTAMP NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_token (
  token TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  expires_at TIMESTAMP
);

-- Recipe hero image (for existing DBs)
ALTER TABLE IF EXISTS recipe_master
  ADD COLUMN IF NOT EXISTS image_path TEXT;

-- Flexible AI context (optional, for health/diet insights etc.)
ALTER TABLE IF EXISTS recipe_master
  ADD COLUMN IF NOT EXISTS ai_context_json JSONB;

-- Store full structured recipe JSON when generated by LLM
ALTER TABLE IF EXISTS recipe_master
  ADD COLUMN IF NOT EXISTS recipe_json JSONB;
 
-- Add password columns to users table for email/password auth
ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS password_salt TEXT;
-- Add designation and permissions for admin users
ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS designation TEXT;
ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS permissions_json JSONB;
-- Add optional profile and business fields for customer users
ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS profile_pic TEXT;
ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS business_details JSONB;
ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS address TEXT;
-- Ensure email is unique so ON CONFLICT (email) works in registration
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_unique ON users(email);

-- Associate search logs with optional user
ALTER TABLE IF EXISTS recipe_search_log
  ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS ingredient_alias (
  id SERIAL PRIMARY KEY,
  alias TEXT NOT NULL UNIQUE,
  canonical_name TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ingredient_alias_canonical ON ingredient_alias(canonical_name);

-- Chat sessions and message timeline (one chat = many messages)
CREATE TABLE IF NOT EXISTS chat_session (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chat_message (
  id SERIAL PRIMARY KEY,
  chat_id INTEGER NOT NULL REFERENCES chat_session(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT,
  recipe_id INTEGER REFERENCES recipe_master(id) ON DELETE SET NULL,
  recipe_json JSONB,
  created_at TIMESTAMP DEFAULT NOW()
);

-- For DBs that still have chat_session_id, migration in init_db() normalizes to chat_id
ALTER TABLE chat_message ADD COLUMN IF NOT EXISTS recipe_id INTEGER REFERENCES recipe_master(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_chat_message_chat_id ON chat_message(chat_id);

-- Content blocks per message (text, recipe, video, ad, cta)
CREATE TABLE IF NOT EXISTS chat_content_block (
  id SERIAL PRIMARY KEY,
  message_id INTEGER NOT NULL REFERENCES chat_message(id) ON DELETE CASCADE,
  block_type TEXT NOT NULL CHECK (block_type IN ('text', 'recipe', 'video', 'ad', 'cta')),
  content_json JSONB NOT NULL,
  display_order INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_content_block_message ON chat_content_block(message_id);

-- Track per-step reactions (likes/dislikes) per user and aggregated counts
CREATE TABLE IF NOT EXISTS step_reaction_user (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  recipe_id INTEGER NOT NULL REFERENCES recipe_master(id) ON DELETE CASCADE,
  step_index INTEGER NOT NULL,
  reaction TEXT NOT NULL CHECK (reaction IN ('like','dislike')),
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE (user_id, recipe_id, step_index)
);

CREATE TABLE IF NOT EXISTS step_reaction_count (
  recipe_id INTEGER NOT NULL REFERENCES recipe_master(id) ON DELETE CASCADE,
  step_index INTEGER NOT NULL,
  likes INTEGER DEFAULT 0,
  dislikes INTEGER DEFAULT 0,
  PRIMARY KEY (recipe_id, step_index)
);

-- Recipe-level reactions (single like/dislike per user, aggregated counts)
CREATE TABLE IF NOT EXISTS recipe_reaction_user (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  recipe_id INTEGER NOT NULL REFERENCES recipe_master(id) ON DELETE CASCADE,
  reaction TEXT NOT NULL CHECK (reaction IN ('like','dislike')),
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE (user_id, recipe_id)
);

-- Optional link to chat session for context when reaction originates from a chat
ALTER TABLE IF EXISTS recipe_reaction_user
  ADD COLUMN IF NOT EXISTS chat_id INTEGER REFERENCES chat_session(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS recipe_reaction_count (
  recipe_id INTEGER NOT NULL REFERENCES recipe_master(id) ON DELETE CASCADE PRIMARY KEY,
  likes INTEGER DEFAULT 0,
  dislikes INTEGER DEFAULT 0
);

-- Recipe reviews & ratings (one per user per recipe, upsertable)
CREATE TABLE IF NOT EXISTS recipe_reviews (
  id          SERIAL PRIMARY KEY,
  user_id     INTEGER REFERENCES users(id) ON DELETE CASCADE,
  recipe_id   INTEGER NOT NULL REFERENCES recipe_master(id) ON DELETE CASCADE,
  rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review_text TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, recipe_id)
);

-- ─── Chef Module ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS chef_profile (
  id                SERIAL PRIMARY KEY,
  user_id           INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  slug              TEXT NOT NULL UNIQUE,
  designation       TEXT,
  cuisine_speciality TEXT,
  cuisine_tags      JSONB NOT NULL DEFAULT '[]',
  experience_years  INTEGER,
  location          TEXT,
  bio               TEXT,
  certifications    JSONB NOT NULL DEFAULT '[]',
  avatar_color      TEXT NOT NULL DEFAULT '#DA7756',
  avatar_url        TEXT,
  banner_url        TEXT,
  youtube_url       TEXT,
  instagram_url     TEXT,
  website_url       TEXT,
  appearance_theme  JSONB,
  plan              TEXT NOT NULL DEFAULT 'free',
  is_verified       BOOLEAN NOT NULL DEFAULT FALSE,
  is_featured       BOOLEAN NOT NULL DEFAULT FALSE,
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  rating            NUMERIC(3,2),
  review_count      INTEGER NOT NULL DEFAULT 0,
  follower_count    INTEGER NOT NULL DEFAULT 0,
  profile_views     INTEGER NOT NULL DEFAULT 0,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chef_follower (
  id           SERIAL PRIMARY KEY,
  chef_id      INTEGER NOT NULL REFERENCES chef_profile(id) ON DELETE CASCADE,
  follower_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  followed_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (chef_id, follower_id)
);

CREATE TABLE IF NOT EXISTS chef_review (
  id         SERIAL PRIMARY KEY,
  chef_id    INTEGER NOT NULL REFERENCES chef_profile(id) ON DELETE CASCADE,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rating     INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment    TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (chef_id, user_id)
);

-- Chef Roles
CREATE TABLE IF NOT EXISTS chef_roles (
  id          SERIAL PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chef_role_mapping (
  id       SERIAL PRIMARY KEY,
  chef_id  INTEGER NOT NULL REFERENCES chef_profile(id) ON DELETE CASCADE,
  role_id  INTEGER NOT NULL REFERENCES chef_roles(id) ON DELETE CASCADE,
  UNIQUE (chef_id, role_id)
);

-- Flexible Category Hierarchy
CREATE TABLE IF NOT EXISTS categories (
  id         SERIAL PRIMARY KEY,
  name       TEXT NOT NULL,
  slug       TEXT NOT NULL UNIQUE,
  parent_id  INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  level      INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Chef-Category mapping (which cuisine categories a chef specialises in)
CREATE TABLE IF NOT EXISTS chef_category_mapping (
  id          SERIAL PRIMARY KEY,
  chef_id     INTEGER NOT NULL REFERENCES chef_profile(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  UNIQUE (chef_id, category_id)
);

-- Chef Reels
CREATE TABLE IF NOT EXISTS chef_reels (
  id               SERIAL PRIMARY KEY,
  chef_id          INTEGER NOT NULL REFERENCES chef_profile(id) ON DELETE CASCADE,
  title            TEXT NOT NULL,
  description      TEXT,
  hashtags         JSONB NOT NULL DEFAULT '[]',
  video_url        TEXT,
  video_file_path  TEXT,
  platform         TEXT,
  thumbnail        TEXT,
  status           TEXT NOT NULL DEFAULT 'active',
  view_count       INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_chef_reels_chef_id ON chef_reels(chef_id);
CREATE INDEX IF NOT EXISTS idx_chef_reels_status  ON chef_reels(status);

-- Recipe-Category mapping
CREATE TABLE IF NOT EXISTS recipe_category_map (
  id          SERIAL PRIMARY KEY,
  recipe_id   INTEGER NOT NULL REFERENCES recipe_master(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  UNIQUE (recipe_id, category_id)
);
